import React, { useState } from 'react';
import { Input, Button, Alert, Typography, Space, Collapse } from 'antd';

const { Text, Link } = Typography;
const { Panel } = Collapse;

export interface DelegationSettingsValue {
  safeAddress: string;
  rolesModifierAddress: string;
  roleKey: string;
}

interface DelegationSettingsProps {
  value: DelegationSettingsValue | null;
  onSave: (value: DelegationSettingsValue) => void;
  onClear: () => void;
  saving?: boolean;
}

const isAddress = (v: string) => /^0x[a-fA-F0-9]{40}$/.test(v.trim());

/**
 * Lets the user opt Smart Automations into executing through a Safe +
 * Zodiac Roles Modifier they've already deployed, instead of executing
 * directly with a plain EOA and MAX_UINT256-or-nothing approvals.
 *
 * This form deliberately never suggests a default address for any field —
 * every value here moves real funds if wrong, so there's nothing to
 * pre-fill safely. See delegation/zodiacRoles.ts for what happens with
 * these values once saved.
 */
export const DelegationSettings: React.FC<DelegationSettingsProps> = ({
  value,
  onSave,
  onClear,
  saving,
}) => {
  const [safeAddress, setSafeAddress] = useState(value?.safeAddress ?? '');
  const [rolesModifierAddress, setRolesModifierAddress] = useState(
    value?.rolesModifierAddress ?? ''
  );
  const [roleKey, setRoleKey] = useState(value?.roleKey ?? '');

  const valid =
    isAddress(safeAddress) &&
    isAddress(rolesModifierAddress) &&
    /^0x[a-fA-F0-9]{64}$/.test(roleKey.trim());

  return (
    <div className="delegation-settings">
      <Alert
        type="info"
        showIcon
        message="Optional: scope automations through a Safe + Zodiac Roles Modifier"
        description={
          <Text>
            By default, automations execute directly from this account, and
            an approve() step (if any) is capped at the amount you set when
            creating the workflow. If you&apos;d rather have on-chain
            enforcement — so the automation literally cannot exceed what a
            role permits, regardless of what the workflow contains — deploy
            a Safe and attach a Zodiac Roles Modifier at{' '}
            <Link href="https://app.roles.gnosisguild.org" target="_blank">
              app.roles.gnosisguild.org
            </Link>
            , grant a role only the specific permissions this automation
            needs, and paste the resulting addresses below. Rabby cannot do
            the deployment or permission setup for you.
          </Text>
        }
        style={{ marginBottom: 16 }}
      />

      <Space direction="vertical" style={{ width: '100%' }} size="middle">
        <div>
          <Text strong>Safe address</Text>
          <Input
            placeholder="0x..."
            value={safeAddress}
            onChange={(e) => setSafeAddress(e.target.value)}
          />
        </div>
        <div>
          <Text strong>Zodiac Roles Modifier address</Text>
          <Input
            placeholder="0x..."
            value={rolesModifierAddress}
            onChange={(e) => setRolesModifierAddress(e.target.value)}
          />
        </div>
        <div>
          <Text strong>Role key (bytes32)</Text>
          <Input
            placeholder="0x..."
            value={roleKey}
            onChange={(e) => setRoleKey(e.target.value)}
          />
        </div>

        <Space>
          <Button
            type="primary"
            disabled={!valid}
            loading={saving}
            onClick={() =>
              onSave({
                safeAddress: safeAddress.trim(),
                rolesModifierAddress: rolesModifierAddress.trim(),
                roleKey: roleKey.trim(),
              })
            }
          >
            Save
          </Button>
          {value && (
            <Button danger onClick={onClear}>
              Stop using role delegation
            </Button>
          )}
        </Space>
      </Space>

      <Collapse ghost style={{ marginTop: 16 }}>
        <Panel header="What exactly does this change?" key="1">
          <Text type="secondary">
            Once saved, every action node in a newly created workflow is
            rewritten to call execTransactionWithRole on your Roles
            Modifier instead of calling the target contract directly. If
            the role you configured doesn&apos;t permit that exact call, the
            transaction reverts instead of executing — including calls
            generated by KeeperHub&apos;s AI path, not just the built-in
            templates. This does not retroactively change automations you
            already created.
          </Text>
        </Panel>
      </Collapse>
    </div>
  );
};
